---
title: "Task 7. Moneta"
author: "Greta Lauruskaite"
date: '2016 m Spalio 7 d'
output: html_document
---

##MONETA

SÀLYGA: Tarkime metama moneta. Jeigu iðkrenta herbas, tai laimite 12 EUR. Jeigu skaièius, tai praloðiate 10 EUR. Bus þaidþiama 100 kartø ir gauti rezultatai sumuojami. 

```{r S}
n = 100
F <- function(n){sum(sample(c(-10, 12), size = n, replace = TRUE))}
#Sugeneruojam funkcijà, kuri po 100 metimø suskaièiuoja gautà laimëjimà
```

* Kokia tikimybë jums turëti teigiamà balansà po 100 kartø? 

```{r S}
prob <- sapply(n, function(ni) mean(replicate(n, F(ni))>0))
prob
# Sugeneruojam tikimybæ, kad balansas po 100 metimø bus teigiamas
```

* Koks balanso pasikliautinis 95% intervalas? 

```{r S}
int <- sapply(n, function(ni) quantile(replicate(n, F(ni)), probs = c(0.025, 0.975)))
colnames(int) <- c(n)
int
# Iðspausdiname intervalus, á kuriuos pateks 95% reikðmiø, matricos pavidale
```

* Kaip atrodo balanso tankis?

```{r S}
plot(density(replicate(n, F(n))), xlab = "Reiksmes", ylab = "Tankis", main = "Balanso tankis", lwd = "4", col = "5")
# Nubraiþome balanso tanká po 100 metimø
```